FROM elixir:1.17.1-otp-27-slim

ARG NODE_VERSION=20.10.0

# Install build dependencies
RUN apt-get update -y && apt-get install -y build-essential git inotify-tools npm \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*

# Prepare build dir
WORKDIR /app

# Install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# Set build ENV
ENV MIX_ENV="dev"

# Install mix dependencies
COPY . ./
RUN mix deps.get

RUN npm install --prefix assets

# Compile the project
RUN mix compile

EXPOSE 4000

# Default Command
CMD ["mix", "phx.server"]